---

version: '3.8'
networks:
  jenkins:

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    # environment:

    #   - http.cors.enabled=true
    #   - http.cors.allow-origin=".*"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    ports:
      - "9200:9200"
    networks:
      - jenkins

  kibana:
    container_name: kibana
    build:
      context: .
      dockerfile: docker/Dockerfile-kibana
    # image: docker.elastic.co/kibana/kibana:7.17.5
    ports:
      - "25601:5601"
    networks:
      - jenkins
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:Z

  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: docker/Dockerfile-jenkins
    # image: jenkins/jenkins:lts
    ports:
      - 18080:8080
      - 50000:50000
    volumes:
  #     #- /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

  elasticvue:
    image: cars10/elasticvue
    ports:
      - 8080:8080
    networks:
      - jenkins
